CC = g++
FLAGS = -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE
IFLAGS = -Iinclude
OBJECTS = main.o stack.o vtor.o my_assert.o hash.o

all: $(OBJECTS)
	$(CC) $(OBJECTS) -o Stack

main.o: main.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

stack.o: stack.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

vtor.o: vtor.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

my_assert.o: my_assert.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

hash.o: hash.cpp
	$(CC) $(FLAGS) $(IFLAGS) -c $^  -o $@

clean:
	rm -f *.o *~ core *~ *.exe
